### ISSUE TITLE
Mean Quick Sort freezes/crashes on some inputs

### ISSUE THREAD

**Issue by easyaspi314** [Gaming32/ArrayV-Extra-Sorts#4]
This seems to be when the array size is not a power of 2 on certain inputs. I am not sure what.

Settings: Array size = 100, sort = reversed

https://user-images.githubusercontent.com/6258309/163306156-ede24c4c-d5a2-44f2-a639-a45bf526b6d4.mp4

It will hang at a random element until it throws an ArrayIndexOutOfBoundsException:
```java
java.lang.ArrayIndexOutOfBoundsException: Index 32768 out of bounds for length 32768
	at io.github.arrayv.sorts.exchange.MeanQuickSort.partition(MeanQuickSort.java:102)
	at io.github.arrayv.sorts.exchange.MeanQuickSort.partition(MeanQuickSort.java:129)
	at io.github.arrayv.sorts.exchange.MeanQuickSort.partition(MeanQuickSort.java:129)
	at io.github.arrayv.sorts.exchange.MeanQuickSort.partition(MeanQuickSort.java:129)
	at io.github.arrayv.sorts.exchange.MeanQuickSort.partition(MeanQuickSort.java:129)
	at io.github.arrayv.sorts.exchange.MeanQuickSort.partition(MeanQuickSort.java:129)
	at io.github.arrayv.sorts.exchange.MeanQuickSort.partition(MeanQuickSort.java:132)
	at io.github.arrayv.sorts.exchange.MeanQuickSort.partition(MeanQuickSort.java:129)
	at io.github.arrayv.sorts.exchange.MeanQuickSort.partition(MeanQuickSort.java:129)
	at io.github.arrayv.sorts.exchange.MeanQuickSort.partition(MeanQuickSort.java:129)
	at io.github.arrayv.sorts.exchange.MeanQuickSort.partition(MeanQuickSort.java:129)
	at io.github.arrayv.sorts.exchange.MeanQuickSort.runSort(MeanQuickSort.java:148)
	at io.github.arrayv.main.RunSort$1.run(RunSort.java:217)
```
The program ends up in an unusable state because `clearAllMarks` also goes out of bounds.
```java
Exception in thread "ComparisonSorting" java.lang.ArrayIndexOutOfBoundsException: Index 32768 out of bounds for length 32768
        at io.github.arrayv.utils.Highlights.clearAllMarks(Highlights.java:208)
        at io.github.arrayv.main.ArrayVisualizer.endSort(ArrayVisualizer.java:1289)
        at io.github.arrayv.main.RunSort$1.run(RunSort.java:240)
```

**Comment by Gaming32** [comment]
Mean Quick Sort is a broken sort that doesn't work. I've tried to figure it out, but I can't. The thing about `clearAllMarks` would apply to any sort that goes out of bounds, so you should make an issue about that on [Gaming32/ArrayV](https://github.com/Gaming32/ArrayV/issues).
